import { test } from 'node:test';
import {
  parseFairyUsi,
  scalashogiCharPair,
  shogigroundDropDests,
  shogigroundMoveDests,
} from '../src/compat.js';
import { initialSfen, parseSfen } from '../src/sfen.js';
import type { Rules } from '../src/types.js';
import { makeUsi, parseUsi } from '../src/util.js';
import { expect } from './debug.js';
import { usiFixture } from './fixtures/usi.js';

test('shogiground dests', () => {
  const pos = parseSfen('standard', initialSfen('standard')).unwrap();
  const dests = shogigroundMoveDests(pos);
  expect(dests.get('7g')?.includes('7f')).toEqual(true);
  expect(dests.get('5i')?.includes('6h')).toEqual(true);
  expect(dests.get('5i')?.includes('6i')).toEqual(false);
});

test('shogiground drop dests', () => {
  const pos = parseSfen('standard', initialSfen('standard')).unwrap();
  const dests1 = shogigroundDropDests(pos);
  expect(dests1.get('sente pawn')).toEqual(undefined);

  const pos2 = parseSfen('standard', '9/9/5k3/9/9/9/9/4K4/9 b N 1').unwrap();
  const dests2 = shogigroundDropDests(pos2);
  const knightDests2 = dests2.get(`${pos2.turn} knight`);
  expect(knightDests2?.includes('5i')).toEqual(true);
  expect(knightDests2?.includes('5h')).toEqual(false);
  expect(knightDests2?.includes('5f')).toEqual(true);
  expect(knightDests2?.includes('5c')).toEqual(true);
  expect(knightDests2?.includes('5b')).toEqual(false);
  expect(knightDests2?.includes('5a')).toEqual(false);
  expect(knightDests2?.includes('4c')).toEqual(false);

  const pos3 = parseSfen('standard', '3rkr3/9/8p/4N4/1B7/9/1SG6/1KS6/9 b LPp 1').unwrap();
  const dests3 = shogigroundDropDests(pos3);
  expect(dests3.get('sente pawn')?.includes('5c')).toEqual(true);
  expect(dests3.get('sente pawn')?.includes('5b')).toEqual(false);
  expect(dests3.get('sente lance')?.includes('5b')).toEqual(true);
});

function convStr(usi: string, rules: Rules = 'standard') {
  const parsedUsi = parseUsi(usi)!;
  return scalashogiCharPair(parsedUsi, rules);
}
test('scalashogiCharPair - moves', () => {
  expect(convStr('1a1b')).toEqual(`#,`);
  expect(convStr('1a1b+')).toEqual(`,#`);
  expect(convStr('1b1a')).toEqual(`,#`);
  expect(convStr('1b1a+')).toEqual(`#,`);
  expect(convStr('1a1c')).toEqual(`#5`);
  expect(convStr('1a1c+')).toEqual(`5#`);
  expect(convStr('1c1a')).toEqual(`5#`);
  expect(convStr('1c1a+')).toEqual(`#5`);
  expect(convStr('1a1d')).toEqual(`#>`);
  expect(convStr('1a1d+')).toEqual(`>#`);
  expect(convStr('1d1a')).toEqual(`>#`);
  expect(convStr('1d1a+')).toEqual(`#>`);
  expect(convStr('1a1e')).toEqual(`#G`);
  expect(convStr('1a1e+')).toEqual(`G#`);
  expect(convStr('1e1a')).toEqual(`G#`);
  expect(convStr('1e1a+')).toEqual(`#G`);
  expect(convStr('1a1f')).toEqual(`#P`);
  expect(convStr('1a1f+')).toEqual(`P#`);
  expect(convStr('1f1a')).toEqual(`P#`);
  expect(convStr('1f1a+')).toEqual(`#P`);
  expect(convStr('1a1g')).toEqual(`#Y`);
  expect(convStr('1a1g+')).toEqual(`Y#`);
  expect(convStr('1g1a')).toEqual(`Y#`);
  expect(convStr('1g1a+')).toEqual(`#Y`);
  expect(convStr('1a1h')).toEqual(`#b`);
  expect(convStr('1a1h+')).toEqual(`b#`);
  expect(convStr('1h1a')).toEqual(`b#`);
  expect(convStr('1h1a+')).toEqual(`#b`);
  expect(convStr('1a1i')).toEqual(`#k`);
  expect(convStr('1a1i+')).toEqual(`k#`);
  expect(convStr('1i1a')).toEqual(`k#`);
  expect(convStr('1i1a+')).toEqual(`#k`);
  expect(convStr('1a2a')).toEqual(`#$`);
  expect(convStr('1a2a+')).toEqual(`$#`);
  expect(convStr('2a1a')).toEqual(`$#`);
  expect(convStr('2a1a+')).toEqual(`#$`);
  expect(convStr('1a2b')).toEqual(`#-`);
  expect(convStr('1a2b+')).toEqual(`-#`);
  expect(convStr('2b1a')).toEqual(`-#`);
  expect(convStr('2b1a+')).toEqual(`#-`);
  expect(convStr('1a2c')).toEqual(`#6`);
  expect(convStr('1a2c+')).toEqual(`6#`);
  expect(convStr('2c1a')).toEqual(`6#`);
  expect(convStr('2c1a+')).toEqual(`#6`);
  expect(convStr('1a2d')).toEqual(`#?`);
  expect(convStr('1a2d+')).toEqual(`?#`);
  expect(convStr('2d1a')).toEqual(`?#`);
  expect(convStr('2d1a+')).toEqual(`#?`);
  expect(convStr('1a2e')).toEqual(`#H`);
  expect(convStr('1a2e+')).toEqual(`H#`);
  expect(convStr('2e1a')).toEqual(`H#`);
  expect(convStr('2e1a+')).toEqual(`#H`);
  expect(convStr('1a2f')).toEqual(`#Q`);
  expect(convStr('1a2f+')).toEqual(`Q#`);
  expect(convStr('2f1a')).toEqual(`Q#`);
  expect(convStr('2f1a+')).toEqual(`#Q`);
  expect(convStr('1a2g')).toEqual(`#Z`);
  expect(convStr('1a2g+')).toEqual(`Z#`);
  expect(convStr('2g1a')).toEqual(`Z#`);
  expect(convStr('2g1a+')).toEqual(`#Z`);
  expect(convStr('1a2h')).toEqual(`#c`);
  expect(convStr('1a2h+')).toEqual(`c#`);
  expect(convStr('2h1a')).toEqual(`c#`);
  expect(convStr('2h1a+')).toEqual(`#c`);
  expect(convStr('1a2i')).toEqual(`#l`);
  expect(convStr('1a2i+')).toEqual(`l#`);
  expect(convStr('2i1a')).toEqual(`l#`);
  expect(convStr('2i1a+')).toEqual(`#l`);
  expect(convStr('1a3a')).toEqual(`#%`);
  expect(convStr('1a3a+')).toEqual(`%#`);
  expect(convStr('3a1a')).toEqual(`%#`);
  expect(convStr('3a1a+')).toEqual(`#%`);
  expect(convStr('1a3b')).toEqual(`#.`);
  expect(convStr('1a3b+')).toEqual(`.#`);
  expect(convStr('3b1a')).toEqual(`.#`);
  expect(convStr('3b1a+')).toEqual(`#.`);
  expect(convStr('1a3c')).toEqual(`#7`);
  expect(convStr('1a3c+')).toEqual(`7#`);
  expect(convStr('3c1a')).toEqual(`7#`);
  expect(convStr('3c1a+')).toEqual(`#7`);
  expect(convStr('1a3d')).toEqual(`#@`);
  expect(convStr('1a3d+')).toEqual(`@#`);
  expect(convStr('3d1a')).toEqual(`@#`);
  expect(convStr('3d1a+')).toEqual(`#@`);
  expect(convStr('1a3e')).toEqual(`#I`);
  expect(convStr('1a3e+')).toEqual(`I#`);
  expect(convStr('3e1a')).toEqual(`I#`);
  expect(convStr('3e1a+')).toEqual(`#I`);
  expect(convStr('1a3f')).toEqual(`#R`);
  expect(convStr('1a3f+')).toEqual(`R#`);
  expect(convStr('3f1a')).toEqual(`R#`);
  expect(convStr('3f1a+')).toEqual(`#R`);
  expect(convStr('1a3g')).toEqual(`#[`);
  expect(convStr('1a3g+')).toEqual(`[#`);
  expect(convStr('3g1a')).toEqual(`[#`);
  expect(convStr('3g1a+')).toEqual(`#[`);
  expect(convStr('1a3h')).toEqual(`#d`);
  expect(convStr('1a3h+')).toEqual(`d#`);
  expect(convStr('3h1a')).toEqual(`d#`);
  expect(convStr('3h1a+')).toEqual(`#d`);
  expect(convStr('1a3i')).toEqual(`#m`);
  expect(convStr('1a3i+')).toEqual(`m#`);
  expect(convStr('3i1a')).toEqual(`m#`);
  expect(convStr('3i1a+')).toEqual(`#m`);
  expect(convStr('1a4a')).toEqual(`#&`);
  expect(convStr('1a4a+')).toEqual(`&#`);
  expect(convStr('4a1a')).toEqual(`&#`);
  expect(convStr('4a1a+')).toEqual(`#&`);
  expect(convStr('1a4b')).toEqual(`#/`);
  expect(convStr('1a4b+')).toEqual(`/#`);
  expect(convStr('4b1a')).toEqual(`/#`);
  expect(convStr('4b1a+')).toEqual(`#/`);
  expect(convStr('1a4c')).toEqual(`#8`);
  expect(convStr('1a4c+')).toEqual(`8#`);
  expect(convStr('4c1a')).toEqual(`8#`);
  expect(convStr('4c1a+')).toEqual(`#8`);
  expect(convStr('1a4d')).toEqual(`#A`);
  expect(convStr('1a4d+')).toEqual(`A#`);
  expect(convStr('4d1a')).toEqual(`A#`);
  expect(convStr('4d1a+')).toEqual(`#A`);
  expect(convStr('1a4e')).toEqual(`#J`);
  expect(convStr('1a4e+')).toEqual(`J#`);
  expect(convStr('4e1a')).toEqual(`J#`);
  expect(convStr('4e1a+')).toEqual(`#J`);
  expect(convStr('1a4f')).toEqual(`#S`);
  expect(convStr('1a4f+')).toEqual(`S#`);
  expect(convStr('4f1a')).toEqual(`S#`);
  expect(convStr('4f1a+')).toEqual(`#S`);
  expect(convStr('1a4g')).toEqual(`#\\`);
  expect(convStr('1a4g+')).toEqual(`\\#`);
  expect(convStr('4g1a')).toEqual(`\\#`);
  expect(convStr('4g1a+')).toEqual(`#\\`);
  expect(convStr('1a4h')).toEqual(`#e`);
  expect(convStr('1a4h+')).toEqual(`e#`);
  expect(convStr('4h1a')).toEqual(`e#`);
  expect(convStr('4h1a+')).toEqual(`#e`);
  expect(convStr('1a4i')).toEqual(`#n`);
  expect(convStr('1a4i+')).toEqual(`n#`);
  expect(convStr('4i1a')).toEqual(`n#`);
  expect(convStr('4i1a+')).toEqual(`#n`);
  expect(convStr('1a5a')).toEqual(`#'`);
  expect(convStr('1a5a+')).toEqual(`'#`);
  expect(convStr('5a1a')).toEqual(`'#`);
  expect(convStr('5a1a+')).toEqual(`#'`);
  expect(convStr('1a5b')).toEqual(`#0`);
  expect(convStr('1a5b+')).toEqual(`0#`);
  expect(convStr('5b1a')).toEqual(`0#`);
  expect(convStr('5b1a+')).toEqual(`#0`);
  expect(convStr('1a5c')).toEqual(`#9`);
  expect(convStr('1a5c+')).toEqual(`9#`);
  expect(convStr('5c1a')).toEqual(`9#`);
  expect(convStr('5c1a+')).toEqual(`#9`);
  expect(convStr('1a5d')).toEqual(`#B`);
  expect(convStr('1a5d+')).toEqual(`B#`);
  expect(convStr('5d1a')).toEqual(`B#`);
  expect(convStr('5d1a+')).toEqual(`#B`);
  expect(convStr('1a5e')).toEqual(`#K`);
  expect(convStr('1a5e+')).toEqual(`K#`);
  expect(convStr('5e1a')).toEqual(`K#`);
  expect(convStr('5e1a+')).toEqual(`#K`);
  expect(convStr('1a5f')).toEqual(`#T`);
  expect(convStr('1a5f+')).toEqual(`T#`);
  expect(convStr('5f1a')).toEqual(`T#`);
  expect(convStr('5f1a+')).toEqual(`#T`);
  expect(convStr('1a5g')).toEqual(`#]`);
  expect(convStr('1a5g+')).toEqual(`]#`);
  expect(convStr('5g1a')).toEqual(`]#`);
  expect(convStr('5g1a+')).toEqual(`#]`);
  expect(convStr('1a5h')).toEqual(`#f`);
  expect(convStr('1a5h+')).toEqual(`f#`);
  expect(convStr('5h1a')).toEqual(`f#`);
  expect(convStr('5h1a+')).toEqual(`#f`);
  expect(convStr('1a5i')).toEqual(`#o`);
  expect(convStr('1a5i+')).toEqual(`o#`);
  expect(convStr('5i1a')).toEqual(`o#`);
  expect(convStr('5i1a+')).toEqual(`#o`);
  expect(convStr('1a6a')).toEqual(`#(`);
  expect(convStr('1a6a+')).toEqual(`(#`);
  expect(convStr('6a1a')).toEqual(`(#`);
  expect(convStr('6a1a+')).toEqual(`#(`);
  expect(convStr('1a6b')).toEqual(`#1`);
  expect(convStr('1a6b+')).toEqual(`1#`);
  expect(convStr('6b1a')).toEqual(`1#`);
  expect(convStr('6b1a+')).toEqual(`#1`);
  expect(convStr('1a6c')).toEqual(`#:`);
  expect(convStr('1a6c+')).toEqual(`:#`);
  expect(convStr('6c1a')).toEqual(`:#`);
  expect(convStr('6c1a+')).toEqual(`#:`);
  expect(convStr('1a6d')).toEqual(`#C`);
  expect(convStr('1a6d+')).toEqual(`C#`);
  expect(convStr('6d1a')).toEqual(`C#`);
  expect(convStr('6d1a+')).toEqual(`#C`);
  expect(convStr('1a6e')).toEqual(`#L`);
  expect(convStr('1a6e+')).toEqual(`L#`);
  expect(convStr('6e1a')).toEqual(`L#`);
  expect(convStr('6e1a+')).toEqual(`#L`);
  expect(convStr('1a6f')).toEqual(`#U`);
  expect(convStr('1a6f+')).toEqual(`U#`);
  expect(convStr('6f1a')).toEqual(`U#`);
  expect(convStr('6f1a+')).toEqual(`#U`);
  expect(convStr('1a6g')).toEqual(`#^`);
  expect(convStr('1a6g+')).toEqual(`^#`);
  expect(convStr('6g1a')).toEqual(`^#`);
  expect(convStr('6g1a+')).toEqual(`#^`);
  expect(convStr('1a6h')).toEqual(`#g`);
  expect(convStr('1a6h+')).toEqual(`g#`);
  expect(convStr('6h1a')).toEqual(`g#`);
  expect(convStr('6h1a+')).toEqual(`#g`);
  expect(convStr('1a6i')).toEqual(`#p`);
  expect(convStr('1a6i+')).toEqual(`p#`);
  expect(convStr('6i1a')).toEqual(`p#`);
  expect(convStr('6i1a+')).toEqual(`#p`);
  expect(convStr('1a7a')).toEqual(`#)`);
  expect(convStr('1a7a+')).toEqual(`)#`);
  expect(convStr('7a1a')).toEqual(`)#`);
  expect(convStr('7a1a+')).toEqual(`#)`);
  expect(convStr('1a7b')).toEqual(`#2`);
  expect(convStr('1a7b+')).toEqual(`2#`);
  expect(convStr('7b1a')).toEqual(`2#`);
  expect(convStr('7b1a+')).toEqual(`#2`);
  expect(convStr('1a7c')).toEqual(`#;`);
  expect(convStr('1a7c+')).toEqual(`;#`);
  expect(convStr('7c1a')).toEqual(`;#`);
  expect(convStr('7c1a+')).toEqual(`#;`);
  expect(convStr('1a7d')).toEqual(`#D`);
  expect(convStr('1a7d+')).toEqual(`D#`);
  expect(convStr('7d1a')).toEqual(`D#`);
  expect(convStr('7d1a+')).toEqual(`#D`);
  expect(convStr('1a7e')).toEqual(`#M`);
  expect(convStr('1a7e+')).toEqual(`M#`);
  expect(convStr('7e1a')).toEqual(`M#`);
  expect(convStr('7e1a+')).toEqual(`#M`);
  expect(convStr('1a7f')).toEqual(`#V`);
  expect(convStr('1a7f+')).toEqual(`V#`);
  expect(convStr('7f1a')).toEqual(`V#`);
  expect(convStr('7f1a+')).toEqual(`#V`);
  expect(convStr('1a7g')).toEqual(`#_`);
  expect(convStr('1a7g+')).toEqual(`_#`);
  expect(convStr('7g1a')).toEqual(`_#`);
  expect(convStr('7g1a+')).toEqual(`#_`);
  expect(convStr('1a7h')).toEqual(`#h`);
  expect(convStr('1a7h+')).toEqual(`h#`);
  expect(convStr('7h1a')).toEqual(`h#`);
  expect(convStr('7h1a+')).toEqual(`#h`);
  expect(convStr('1a7i')).toEqual(`#q`);
  expect(convStr('1a7i+')).toEqual(`q#`);
  expect(convStr('7i1a')).toEqual(`q#`);
  expect(convStr('7i1a+')).toEqual(`#q`);
  expect(convStr('1a8a')).toEqual(`#*`);
  expect(convStr('1a8a+')).toEqual(`*#`);
  expect(convStr('8a1a')).toEqual(`*#`);
  expect(convStr('8a1a+')).toEqual(`#*`);
  expect(convStr('1a8b')).toEqual(`#3`);
  expect(convStr('1a8b+')).toEqual(`3#`);
  expect(convStr('8b1a')).toEqual(`3#`);
  expect(convStr('8b1a+')).toEqual(`#3`);
  expect(convStr('1a8c')).toEqual(`#<`);
  expect(convStr('1a8c+')).toEqual(`<#`);
  expect(convStr('8c1a')).toEqual(`<#`);
  expect(convStr('8c1a+')).toEqual(`#<`);
  expect(convStr('1a8d')).toEqual(`#E`);
  expect(convStr('1a8d+')).toEqual(`E#`);
  expect(convStr('8d1a')).toEqual(`E#`);
  expect(convStr('8d1a+')).toEqual(`#E`);
  expect(convStr('1a8e')).toEqual(`#N`);
  expect(convStr('1a8e+')).toEqual(`N#`);
  expect(convStr('8e1a')).toEqual(`N#`);
  expect(convStr('8e1a+')).toEqual(`#N`);
  expect(convStr('1a8f')).toEqual(`#W`);
  expect(convStr('1a8f+')).toEqual(`W#`);
  expect(convStr('8f1a')).toEqual(`W#`);
  expect(convStr('8f1a+')).toEqual(`#W`);
  expect(convStr('1a8g')).toEqual(`#\``);
  expect(convStr('1a8g+')).toEqual(`\`#`);
  expect(convStr('8g1a')).toEqual(`\`#`);
  expect(convStr('8g1a+')).toEqual(`#\``);
  expect(convStr('1a8h')).toEqual(`#i`);
  expect(convStr('1a8h+')).toEqual(`i#`);
  expect(convStr('8h1a')).toEqual(`i#`);
  expect(convStr('8h1a+')).toEqual(`#i`);
  expect(convStr('1a8i')).toEqual(`#r`);
  expect(convStr('1a8i+')).toEqual(`r#`);
  expect(convStr('8i1a')).toEqual(`r#`);
  expect(convStr('8i1a+')).toEqual(`#r`);
  expect(convStr('1a9a')).toEqual(`#+`);
  expect(convStr('1a9a+')).toEqual('+#');
  expect(convStr('9a1a')).toEqual('+#');
  expect(convStr('9a1a+')).toEqual(`#+`);
  expect(convStr('1a9b')).toEqual(`#4`);
  expect(convStr('1a9b+')).toEqual(`4#`);
  expect(convStr('9b1a')).toEqual(`4#`);
  expect(convStr('9b1a+')).toEqual(`#4`);
  expect(convStr('1a9c')).toEqual(`#=`);
  expect(convStr('1a9c+')).toEqual(`=#`);
  expect(convStr('9c1a')).toEqual(`=#`);
  expect(convStr('9c1a+')).toEqual(`#=`);
  expect(convStr('1a9d')).toEqual(`#F`);
  expect(convStr('1a9d+')).toEqual(`F#`);
  expect(convStr('9d1a')).toEqual(`F#`);
  expect(convStr('9d1a+')).toEqual(`#F`);
  expect(convStr('1a9e')).toEqual(`#O`);
  expect(convStr('1a9e+')).toEqual(`O#`);
  expect(convStr('9e1a')).toEqual(`O#`);
  expect(convStr('9e1a+')).toEqual(`#O`);
  expect(convStr('1a9f')).toEqual(`#X`);
  expect(convStr('1a9f+')).toEqual(`X#`);
  expect(convStr('9f1a')).toEqual(`X#`);
  expect(convStr('9f1a+')).toEqual(`#X`);
  expect(convStr('1a9g')).toEqual(`#a`);
  expect(convStr('1a9g+')).toEqual(`a#`);
  expect(convStr('9g1a')).toEqual(`a#`);
  expect(convStr('9g1a+')).toEqual(`#a`);
  expect(convStr('1a9h')).toEqual(`#j`);
  expect(convStr('1a9h+')).toEqual(`j#`);
  expect(convStr('9h1a')).toEqual(`j#`);
  expect(convStr('9h1a+')).toEqual(`#j`);
  expect(convStr('1a9i')).toEqual(`#s`);
  expect(convStr('1a9i+')).toEqual(`s#`);
  expect(convStr('9i1a')).toEqual(`s#`);
  expect(convStr('9i1a+')).toEqual(`#s`);
});

test('scalashogiCharPair - drops', () => {
  expect(convStr('P*1a')).toEqual(`#z`);
  expect(convStr('L*1a')).toEqual(`#y`);
  expect(convStr('N*1a')).toEqual(`#x`);
  expect(convStr('S*1a')).toEqual(`#w`);
  expect(convStr('G*1a')).toEqual(`#v`);
  expect(convStr('B*1a')).toEqual(`#u`);
  expect(convStr('R*1a')).toEqual(`#t`);
  expect(convStr('P*1b')).toEqual(`,z`);
  expect(convStr('L*1b')).toEqual(`,y`);
  expect(convStr('N*1b')).toEqual(`,x`);
  expect(convStr('S*1b')).toEqual(`,w`);
  expect(convStr('G*1b')).toEqual(`,v`);
  expect(convStr('B*1b')).toEqual(`,u`);
  expect(convStr('R*1b')).toEqual(`,t`);
  expect(convStr('P*1c')).toEqual(`5z`);
  expect(convStr('L*1c')).toEqual(`5y`);
  expect(convStr('N*1c')).toEqual(`5x`);
  expect(convStr('S*1c')).toEqual(`5w`);
  expect(convStr('G*1c')).toEqual(`5v`);
  expect(convStr('B*1c')).toEqual(`5u`);
  expect(convStr('R*1c')).toEqual(`5t`);
  expect(convStr('P*1d')).toEqual(`>z`);
  expect(convStr('L*1d')).toEqual(`>y`);
  expect(convStr('N*1d')).toEqual(`>x`);
  expect(convStr('S*1d')).toEqual(`>w`);
  expect(convStr('G*1d')).toEqual(`>v`);
  expect(convStr('B*1d')).toEqual(`>u`);
  expect(convStr('R*1d')).toEqual(`>t`);
  expect(convStr('P*1e')).toEqual(`Gz`);
  expect(convStr('L*1e')).toEqual(`Gy`);
  expect(convStr('N*1e')).toEqual(`Gx`);
  expect(convStr('S*1e')).toEqual(`Gw`);
  expect(convStr('G*1e')).toEqual(`Gv`);
  expect(convStr('B*1e')).toEqual(`Gu`);
  expect(convStr('R*1e')).toEqual(`Gt`);
  expect(convStr('P*1f')).toEqual(`Pz`);
  expect(convStr('L*1f')).toEqual(`Py`);
  expect(convStr('N*1f')).toEqual(`Px`);
  expect(convStr('S*1f')).toEqual(`Pw`);
  expect(convStr('G*1f')).toEqual(`Pv`);
  expect(convStr('B*1f')).toEqual(`Pu`);
  expect(convStr('R*1f')).toEqual(`Pt`);
  expect(convStr('P*1g')).toEqual(`Yz`);
  expect(convStr('L*1g')).toEqual(`Yy`);
  expect(convStr('N*1g')).toEqual(`Yx`);
  expect(convStr('S*1g')).toEqual(`Yw`);
  expect(convStr('G*1g')).toEqual(`Yv`);
  expect(convStr('B*1g')).toEqual(`Yu`);
  expect(convStr('R*1g')).toEqual(`Yt`);
  expect(convStr('P*1h')).toEqual(`bz`);
  expect(convStr('L*1h')).toEqual(`by`);
  expect(convStr('N*1h')).toEqual(`bx`);
  expect(convStr('S*1h')).toEqual(`bw`);
  expect(convStr('G*1h')).toEqual(`bv`);
  expect(convStr('B*1h')).toEqual(`bu`);
  expect(convStr('R*1h')).toEqual(`bt`);
  expect(convStr('P*1i')).toEqual(`kz`);
  expect(convStr('L*1i')).toEqual(`ky`);
  expect(convStr('N*1i')).toEqual(`kx`);
  expect(convStr('S*1i')).toEqual(`kw`);
  expect(convStr('G*1i')).toEqual(`kv`);
  expect(convStr('B*1i')).toEqual(`ku`);
  expect(convStr('R*1i')).toEqual(`kt`);
  expect(convStr('P*2a')).toEqual(`$z`);
  expect(convStr('L*2a')).toEqual(`$y`);
  expect(convStr('N*2a')).toEqual(`$x`);
  expect(convStr('S*2a')).toEqual(`$w`);
  expect(convStr('G*2a')).toEqual(`$v`);
  expect(convStr('B*2a')).toEqual(`$u`);
  expect(convStr('R*2a')).toEqual(`$t`);
  expect(convStr('P*2b')).toEqual(`-z`);
  expect(convStr('L*2b')).toEqual(`-y`);
  expect(convStr('N*2b')).toEqual(`-x`);
  expect(convStr('S*2b')).toEqual(`-w`);
  expect(convStr('G*2b')).toEqual(`-v`);
  expect(convStr('B*2b')).toEqual(`-u`);
  expect(convStr('R*2b')).toEqual(`-t`);
  expect(convStr('P*2c')).toEqual(`6z`);
  expect(convStr('L*2c')).toEqual(`6y`);
  expect(convStr('N*2c')).toEqual(`6x`);
  expect(convStr('S*2c')).toEqual(`6w`);
  expect(convStr('G*2c')).toEqual(`6v`);
  expect(convStr('B*2c')).toEqual(`6u`);
  expect(convStr('R*2c')).toEqual(`6t`);
  expect(convStr('P*2d')).toEqual(`?z`);
  expect(convStr('L*2d')).toEqual(`?y`);
  expect(convStr('N*2d')).toEqual(`?x`);
  expect(convStr('S*2d')).toEqual(`?w`);
  expect(convStr('G*2d')).toEqual(`?v`);
  expect(convStr('B*2d')).toEqual(`?u`);
  expect(convStr('R*2d')).toEqual(`?t`);
  expect(convStr('P*2e')).toEqual(`Hz`);
  expect(convStr('L*2e')).toEqual(`Hy`);
  expect(convStr('N*2e')).toEqual(`Hx`);
  expect(convStr('S*2e')).toEqual(`Hw`);
  expect(convStr('G*2e')).toEqual(`Hv`);
  expect(convStr('B*2e')).toEqual(`Hu`);
  expect(convStr('R*2e')).toEqual(`Ht`);
  expect(convStr('P*2f')).toEqual(`Qz`);
  expect(convStr('L*2f')).toEqual(`Qy`);
  expect(convStr('N*2f')).toEqual(`Qx`);
  expect(convStr('S*2f')).toEqual(`Qw`);
  expect(convStr('G*2f')).toEqual(`Qv`);
  expect(convStr('B*2f')).toEqual(`Qu`);
  expect(convStr('R*2f')).toEqual(`Qt`);
  expect(convStr('P*2g')).toEqual(`Zz`);
  expect(convStr('L*2g')).toEqual(`Zy`);
  expect(convStr('N*2g')).toEqual(`Zx`);
  expect(convStr('S*2g')).toEqual(`Zw`);
  expect(convStr('G*2g')).toEqual(`Zv`);
  expect(convStr('B*2g')).toEqual(`Zu`);
  expect(convStr('R*2g')).toEqual(`Zt`);
  expect(convStr('P*2h')).toEqual(`cz`);
  expect(convStr('L*2h')).toEqual(`cy`);
  expect(convStr('N*2h')).toEqual(`cx`);
  expect(convStr('S*2h')).toEqual(`cw`);
  expect(convStr('G*2h')).toEqual(`cv`);
  expect(convStr('B*2h')).toEqual(`cu`);
  expect(convStr('R*2h')).toEqual(`ct`);
  expect(convStr('P*2i')).toEqual(`lz`);
  expect(convStr('L*2i')).toEqual(`ly`);
  expect(convStr('N*2i')).toEqual(`lx`);
  expect(convStr('S*2i')).toEqual(`lw`);
  expect(convStr('G*2i')).toEqual(`lv`);
  expect(convStr('B*2i')).toEqual(`lu`);
  expect(convStr('R*2i')).toEqual(`lt`);
  expect(convStr('P*3a')).toEqual(`%z`);
  expect(convStr('L*3a')).toEqual(`%y`);
  expect(convStr('N*3a')).toEqual(`%x`);
  expect(convStr('S*3a')).toEqual(`%w`);
  expect(convStr('G*3a')).toEqual(`%v`);
  expect(convStr('B*3a')).toEqual(`%u`);
  expect(convStr('R*3a')).toEqual(`%t`);
  expect(convStr('P*3b')).toEqual(`.z`);
  expect(convStr('L*3b')).toEqual(`.y`);
  expect(convStr('N*3b')).toEqual(`.x`);
  expect(convStr('S*3b')).toEqual(`.w`);
  expect(convStr('G*3b')).toEqual(`.v`);
  expect(convStr('B*3b')).toEqual(`.u`);
  expect(convStr('R*3b')).toEqual(`.t`);
  expect(convStr('P*3c')).toEqual(`7z`);
  expect(convStr('L*3c')).toEqual(`7y`);
  expect(convStr('N*3c')).toEqual(`7x`);
  expect(convStr('S*3c')).toEqual(`7w`);
  expect(convStr('G*3c')).toEqual(`7v`);
  expect(convStr('B*3c')).toEqual(`7u`);
  expect(convStr('R*3c')).toEqual(`7t`);
  expect(convStr('P*3d')).toEqual(`@z`);
  expect(convStr('L*3d')).toEqual(`@y`);
  expect(convStr('N*3d')).toEqual(`@x`);
  expect(convStr('S*3d')).toEqual(`@w`);
  expect(convStr('G*3d')).toEqual(`@v`);
  expect(convStr('B*3d')).toEqual(`@u`);
  expect(convStr('R*3d')).toEqual(`@t`);
  expect(convStr('P*3e')).toEqual(`Iz`);
  expect(convStr('L*3e')).toEqual(`Iy`);
  expect(convStr('N*3e')).toEqual(`Ix`);
  expect(convStr('S*3e')).toEqual(`Iw`);
  expect(convStr('G*3e')).toEqual(`Iv`);
  expect(convStr('B*3e')).toEqual(`Iu`);
  expect(convStr('R*3e')).toEqual(`It`);
  expect(convStr('P*3f')).toEqual(`Rz`);
  expect(convStr('L*3f')).toEqual(`Ry`);
  expect(convStr('N*3f')).toEqual(`Rx`);
  expect(convStr('S*3f')).toEqual(`Rw`);
  expect(convStr('G*3f')).toEqual(`Rv`);
  expect(convStr('B*3f')).toEqual(`Ru`);
  expect(convStr('R*3f')).toEqual(`Rt`);
  expect(convStr('P*3g')).toEqual(`[z`);
  expect(convStr('L*3g')).toEqual(`[y`);
  expect(convStr('N*3g')).toEqual(`[x`);
  expect(convStr('S*3g')).toEqual(`[w`);
  expect(convStr('G*3g')).toEqual(`[v`);
  expect(convStr('B*3g')).toEqual(`[u`);
  expect(convStr('R*3g')).toEqual(`[t`);
  expect(convStr('P*3h')).toEqual(`dz`);
  expect(convStr('L*3h')).toEqual(`dy`);
  expect(convStr('N*3h')).toEqual(`dx`);
  expect(convStr('S*3h')).toEqual(`dw`);
  expect(convStr('G*3h')).toEqual(`dv`);
  expect(convStr('B*3h')).toEqual(`du`);
  expect(convStr('R*3h')).toEqual(`dt`);
  expect(convStr('P*3i')).toEqual(`mz`);
  expect(convStr('L*3i')).toEqual(`my`);
  expect(convStr('N*3i')).toEqual(`mx`);
  expect(convStr('S*3i')).toEqual(`mw`);
  expect(convStr('G*3i')).toEqual(`mv`);
  expect(convStr('B*3i')).toEqual(`mu`);
  expect(convStr('R*3i')).toEqual(`mt`);
  expect(convStr('P*4a')).toEqual(`&z`);
  expect(convStr('L*4a')).toEqual(`&y`);
  expect(convStr('N*4a')).toEqual(`&x`);
  expect(convStr('S*4a')).toEqual(`&w`);
  expect(convStr('G*4a')).toEqual(`&v`);
  expect(convStr('B*4a')).toEqual(`&u`);
  expect(convStr('R*4a')).toEqual(`&t`);
  expect(convStr('P*4b')).toEqual(`/z`);
  expect(convStr('L*4b')).toEqual(`/y`);
  expect(convStr('N*4b')).toEqual(`/x`);
  expect(convStr('S*4b')).toEqual(`/w`);
  expect(convStr('G*4b')).toEqual(`/v`);
  expect(convStr('B*4b')).toEqual(`/u`);
  expect(convStr('R*4b')).toEqual(`/t`);
  expect(convStr('P*4c')).toEqual(`8z`);
  expect(convStr('L*4c')).toEqual(`8y`);
  expect(convStr('N*4c')).toEqual(`8x`);
  expect(convStr('S*4c')).toEqual(`8w`);
  expect(convStr('G*4c')).toEqual(`8v`);
  expect(convStr('B*4c')).toEqual(`8u`);
  expect(convStr('R*4c')).toEqual(`8t`);
  expect(convStr('P*4d')).toEqual(`Az`);
  expect(convStr('L*4d')).toEqual(`Ay`);
  expect(convStr('N*4d')).toEqual(`Ax`);
  expect(convStr('S*4d')).toEqual(`Aw`);
  expect(convStr('G*4d')).toEqual(`Av`);
  expect(convStr('B*4d')).toEqual(`Au`);
  expect(convStr('R*4d')).toEqual(`At`);
  expect(convStr('P*4e')).toEqual(`Jz`);
  expect(convStr('L*4e')).toEqual(`Jy`);
  expect(convStr('N*4e')).toEqual(`Jx`);
  expect(convStr('S*4e')).toEqual(`Jw`);
  expect(convStr('G*4e')).toEqual(`Jv`);
  expect(convStr('B*4e')).toEqual(`Ju`);
  expect(convStr('R*4e')).toEqual(`Jt`);
  expect(convStr('P*4f')).toEqual(`Sz`);
  expect(convStr('L*4f')).toEqual(`Sy`);
  expect(convStr('N*4f')).toEqual(`Sx`);
  expect(convStr('S*4f')).toEqual(`Sw`);
  expect(convStr('G*4f')).toEqual(`Sv`);
  expect(convStr('B*4f')).toEqual(`Su`);
  expect(convStr('R*4f')).toEqual(`St`);
  expect(convStr('P*4g')).toEqual(`\\z`);
  expect(convStr('L*4g')).toEqual(`\\y`);
  expect(convStr('N*4g')).toEqual(`\\x`);
  expect(convStr('S*4g')).toEqual(`\\w`);
  expect(convStr('G*4g')).toEqual(`\\v`);
  expect(convStr('B*4g')).toEqual(`\\u`);
  expect(convStr('R*4g')).toEqual(`\\t`);
  expect(convStr('P*4h')).toEqual(`ez`);
  expect(convStr('L*4h')).toEqual(`ey`);
  expect(convStr('N*4h')).toEqual(`ex`);
  expect(convStr('S*4h')).toEqual(`ew`);
  expect(convStr('G*4h')).toEqual(`ev`);
  expect(convStr('B*4h')).toEqual(`eu`);
  expect(convStr('R*4h')).toEqual(`et`);
  expect(convStr('P*4i')).toEqual(`nz`);
  expect(convStr('L*4i')).toEqual(`ny`);
  expect(convStr('N*4i')).toEqual(`nx`);
  expect(convStr('S*4i')).toEqual(`nw`);
  expect(convStr('G*4i')).toEqual(`nv`);
  expect(convStr('B*4i')).toEqual(`nu`);
  expect(convStr('R*4i')).toEqual(`nt`);
  expect(convStr('P*5a')).toEqual(`'z`);
  expect(convStr('L*5a')).toEqual(`'y`);
  expect(convStr('N*5a')).toEqual(`'x`);
  expect(convStr('S*5a')).toEqual(`'w`);
  expect(convStr('G*5a')).toEqual(`'v`);
  expect(convStr('B*5a')).toEqual(`'u`);
  expect(convStr('R*5a')).toEqual(`'t`);
  expect(convStr('P*5b')).toEqual(`0z`);
  expect(convStr('L*5b')).toEqual(`0y`);
  expect(convStr('N*5b')).toEqual(`0x`);
  expect(convStr('S*5b')).toEqual(`0w`);
  expect(convStr('G*5b')).toEqual(`0v`);
  expect(convStr('B*5b')).toEqual(`0u`);
  expect(convStr('R*5b')).toEqual(`0t`);
  expect(convStr('P*5c')).toEqual(`9z`);
  expect(convStr('L*5c')).toEqual(`9y`);
  expect(convStr('N*5c')).toEqual(`9x`);
  expect(convStr('S*5c')).toEqual(`9w`);
  expect(convStr('G*5c')).toEqual(`9v`);
  expect(convStr('B*5c')).toEqual(`9u`);
  expect(convStr('R*5c')).toEqual(`9t`);
  expect(convStr('P*5d')).toEqual(`Bz`);
  expect(convStr('L*5d')).toEqual(`By`);
  expect(convStr('N*5d')).toEqual(`Bx`);
  expect(convStr('S*5d')).toEqual(`Bw`);
  expect(convStr('G*5d')).toEqual(`Bv`);
  expect(convStr('B*5d')).toEqual(`Bu`);
  expect(convStr('R*5d')).toEqual(`Bt`);
  expect(convStr('P*5e')).toEqual(`Kz`);
  expect(convStr('L*5e')).toEqual(`Ky`);
  expect(convStr('N*5e')).toEqual(`Kx`);
  expect(convStr('S*5e')).toEqual(`Kw`);
  expect(convStr('G*5e')).toEqual(`Kv`);
  expect(convStr('B*5e')).toEqual(`Ku`);
  expect(convStr('R*5e')).toEqual(`Kt`);
  expect(convStr('P*5f')).toEqual(`Tz`);
  expect(convStr('L*5f')).toEqual(`Ty`);
  expect(convStr('N*5f')).toEqual(`Tx`);
  expect(convStr('S*5f')).toEqual(`Tw`);
  expect(convStr('G*5f')).toEqual(`Tv`);
  expect(convStr('B*5f')).toEqual(`Tu`);
  expect(convStr('R*5f')).toEqual(`Tt`);
  expect(convStr('P*5g')).toEqual(`]z`);
  expect(convStr('L*5g')).toEqual(`]y`);
  expect(convStr('N*5g')).toEqual(`]x`);
  expect(convStr('S*5g')).toEqual(`]w`);
  expect(convStr('G*5g')).toEqual(`]v`);
  expect(convStr('B*5g')).toEqual(`]u`);
  expect(convStr('R*5g')).toEqual(`]t`);
  expect(convStr('P*5h')).toEqual(`fz`);
  expect(convStr('L*5h')).toEqual(`fy`);
  expect(convStr('N*5h')).toEqual(`fx`);
  expect(convStr('S*5h')).toEqual(`fw`);
  expect(convStr('G*5h')).toEqual(`fv`);
  expect(convStr('B*5h')).toEqual(`fu`);
  expect(convStr('R*5h')).toEqual(`ft`);
  expect(convStr('P*5i')).toEqual(`oz`);
  expect(convStr('L*5i')).toEqual(`oy`);
  expect(convStr('N*5i')).toEqual(`ox`);
  expect(convStr('S*5i')).toEqual(`ow`);
  expect(convStr('G*5i')).toEqual(`ov`);
  expect(convStr('B*5i')).toEqual(`ou`);
  expect(convStr('R*5i')).toEqual(`ot`);
  expect(convStr('P*6a')).toEqual(`(z`);
  expect(convStr('L*6a')).toEqual(`(y`);
  expect(convStr('N*6a')).toEqual(`(x`);
  expect(convStr('S*6a')).toEqual(`(w`);
  expect(convStr('G*6a')).toEqual(`(v`);
  expect(convStr('B*6a')).toEqual(`(u`);
  expect(convStr('R*6a')).toEqual(`(t`);
  expect(convStr('P*6b')).toEqual(`1z`);
  expect(convStr('L*6b')).toEqual(`1y`);
  expect(convStr('N*6b')).toEqual(`1x`);
  expect(convStr('S*6b')).toEqual(`1w`);
  expect(convStr('G*6b')).toEqual(`1v`);
  expect(convStr('B*6b')).toEqual(`1u`);
  expect(convStr('R*6b')).toEqual(`1t`);
  expect(convStr('P*6c')).toEqual(`:z`);
  expect(convStr('L*6c')).toEqual(`:y`);
  expect(convStr('N*6c')).toEqual(`:x`);
  expect(convStr('S*6c')).toEqual(`:w`);
  expect(convStr('G*6c')).toEqual(`:v`);
  expect(convStr('B*6c')).toEqual(`:u`);
  expect(convStr('R*6c')).toEqual(`:t`);
  expect(convStr('P*6d')).toEqual(`Cz`);
  expect(convStr('L*6d')).toEqual(`Cy`);
  expect(convStr('N*6d')).toEqual(`Cx`);
  expect(convStr('S*6d')).toEqual(`Cw`);
  expect(convStr('G*6d')).toEqual(`Cv`);
  expect(convStr('B*6d')).toEqual(`Cu`);
  expect(convStr('R*6d')).toEqual(`Ct`);
  expect(convStr('P*6e')).toEqual(`Lz`);
  expect(convStr('L*6e')).toEqual(`Ly`);
  expect(convStr('N*6e')).toEqual(`Lx`);
  expect(convStr('S*6e')).toEqual(`Lw`);
  expect(convStr('G*6e')).toEqual(`Lv`);
  expect(convStr('B*6e')).toEqual(`Lu`);
  expect(convStr('R*6e')).toEqual(`Lt`);
  expect(convStr('P*6f')).toEqual(`Uz`);
  expect(convStr('L*6f')).toEqual(`Uy`);
  expect(convStr('N*6f')).toEqual(`Ux`);
  expect(convStr('S*6f')).toEqual(`Uw`);
  expect(convStr('G*6f')).toEqual(`Uv`);
  expect(convStr('B*6f')).toEqual(`Uu`);
  expect(convStr('R*6f')).toEqual(`Ut`);
  expect(convStr('P*6g')).toEqual(`^z`);
  expect(convStr('L*6g')).toEqual(`^y`);
  expect(convStr('N*6g')).toEqual(`^x`);
  expect(convStr('S*6g')).toEqual(`^w`);
  expect(convStr('G*6g')).toEqual(`^v`);
  expect(convStr('B*6g')).toEqual(`^u`);
  expect(convStr('R*6g')).toEqual(`^t`);
  expect(convStr('P*6h')).toEqual(`gz`);
  expect(convStr('L*6h')).toEqual(`gy`);
  expect(convStr('N*6h')).toEqual(`gx`);
  expect(convStr('S*6h')).toEqual(`gw`);
  expect(convStr('G*6h')).toEqual(`gv`);
  expect(convStr('B*6h')).toEqual(`gu`);
  expect(convStr('R*6h')).toEqual(`gt`);
  expect(convStr('P*6i')).toEqual(`pz`);
  expect(convStr('L*6i')).toEqual(`py`);
  expect(convStr('N*6i')).toEqual(`px`);
  expect(convStr('S*6i')).toEqual(`pw`);
  expect(convStr('G*6i')).toEqual(`pv`);
  expect(convStr('B*6i')).toEqual(`pu`);
  expect(convStr('R*6i')).toEqual(`pt`);
  expect(convStr('P*7a')).toEqual(`)z`);
  expect(convStr('L*7a')).toEqual(`)y`);
  expect(convStr('N*7a')).toEqual(`)x`);
  expect(convStr('S*7a')).toEqual(`)w`);
  expect(convStr('G*7a')).toEqual(`)v`);
  expect(convStr('B*7a')).toEqual(`)u`);
  expect(convStr('R*7a')).toEqual(`)t`);
  expect(convStr('P*7b')).toEqual(`2z`);
  expect(convStr('L*7b')).toEqual(`2y`);
  expect(convStr('N*7b')).toEqual(`2x`);
  expect(convStr('S*7b')).toEqual(`2w`);
  expect(convStr('G*7b')).toEqual(`2v`);
  expect(convStr('B*7b')).toEqual(`2u`);
  expect(convStr('R*7b')).toEqual(`2t`);
  expect(convStr('P*7c')).toEqual(`;z`);
  expect(convStr('L*7c')).toEqual(`;y`);
  expect(convStr('N*7c')).toEqual(`;x`);
  expect(convStr('S*7c')).toEqual(`;w`);
  expect(convStr('G*7c')).toEqual(`;v`);
  expect(convStr('B*7c')).toEqual(`;u`);
  expect(convStr('R*7c')).toEqual(`;t`);
  expect(convStr('P*7d')).toEqual(`Dz`);
  expect(convStr('L*7d')).toEqual(`Dy`);
  expect(convStr('N*7d')).toEqual(`Dx`);
  expect(convStr('S*7d')).toEqual(`Dw`);
  expect(convStr('G*7d')).toEqual(`Dv`);
  expect(convStr('B*7d')).toEqual(`Du`);
  expect(convStr('R*7d')).toEqual(`Dt`);
  expect(convStr('P*7e')).toEqual(`Mz`);
  expect(convStr('L*7e')).toEqual(`My`);
  expect(convStr('N*7e')).toEqual(`Mx`);
  expect(convStr('S*7e')).toEqual(`Mw`);
  expect(convStr('G*7e')).toEqual(`Mv`);
  expect(convStr('B*7e')).toEqual(`Mu`);
  expect(convStr('R*7e')).toEqual(`Mt`);
  expect(convStr('P*7f')).toEqual(`Vz`);
  expect(convStr('L*7f')).toEqual(`Vy`);
  expect(convStr('N*7f')).toEqual(`Vx`);
  expect(convStr('S*7f')).toEqual(`Vw`);
  expect(convStr('G*7f')).toEqual(`Vv`);
  expect(convStr('B*7f')).toEqual(`Vu`);
  expect(convStr('R*7f')).toEqual(`Vt`);
  expect(convStr('P*7g')).toEqual(`_z`);
  expect(convStr('L*7g')).toEqual(`_y`);
  expect(convStr('N*7g')).toEqual(`_x`);
  expect(convStr('S*7g')).toEqual(`_w`);
  expect(convStr('G*7g')).toEqual(`_v`);
  expect(convStr('B*7g')).toEqual(`_u`);
  expect(convStr('R*7g')).toEqual(`_t`);
  expect(convStr('P*7h')).toEqual(`hz`);
  expect(convStr('L*7h')).toEqual(`hy`);
  expect(convStr('N*7h')).toEqual(`hx`);
  expect(convStr('S*7h')).toEqual(`hw`);
  expect(convStr('G*7h')).toEqual(`hv`);
  expect(convStr('B*7h')).toEqual(`hu`);
  expect(convStr('R*7h')).toEqual(`ht`);
  expect(convStr('P*7i')).toEqual(`qz`);
  expect(convStr('L*7i')).toEqual(`qy`);
  expect(convStr('N*7i')).toEqual(`qx`);
  expect(convStr('S*7i')).toEqual(`qw`);
  expect(convStr('G*7i')).toEqual(`qv`);
  expect(convStr('B*7i')).toEqual(`qu`);
  expect(convStr('R*7i')).toEqual(`qt`);
  expect(convStr('P*8a')).toEqual(`*z`);
  expect(convStr('L*8a')).toEqual(`*y`);
  expect(convStr('N*8a')).toEqual(`*x`);
  expect(convStr('S*8a')).toEqual(`*w`);
  expect(convStr('G*8a')).toEqual(`*v`);
  expect(convStr('B*8a')).toEqual(`*u`);
  expect(convStr('R*8a')).toEqual(`*t`);
  expect(convStr('P*8b')).toEqual(`3z`);
  expect(convStr('L*8b')).toEqual(`3y`);
  expect(convStr('N*8b')).toEqual(`3x`);
  expect(convStr('S*8b')).toEqual(`3w`);
  expect(convStr('G*8b')).toEqual(`3v`);
  expect(convStr('B*8b')).toEqual(`3u`);
  expect(convStr('R*8b')).toEqual(`3t`);
  expect(convStr('P*8c')).toEqual(`<z`);
  expect(convStr('L*8c')).toEqual(`<y`);
  expect(convStr('N*8c')).toEqual(`<x`);
  expect(convStr('S*8c')).toEqual(`<w`);
  expect(convStr('G*8c')).toEqual(`<v`);
  expect(convStr('B*8c')).toEqual(`<u`);
  expect(convStr('R*8c')).toEqual(`<t`);
  expect(convStr('P*8d')).toEqual(`Ez`);
  expect(convStr('L*8d')).toEqual(`Ey`);
  expect(convStr('N*8d')).toEqual(`Ex`);
  expect(convStr('S*8d')).toEqual(`Ew`);
  expect(convStr('G*8d')).toEqual(`Ev`);
  expect(convStr('B*8d')).toEqual(`Eu`);
  expect(convStr('R*8d')).toEqual(`Et`);
  expect(convStr('P*8e')).toEqual(`Nz`);
  expect(convStr('L*8e')).toEqual(`Ny`);
  expect(convStr('N*8e')).toEqual(`Nx`);
  expect(convStr('S*8e')).toEqual(`Nw`);
  expect(convStr('G*8e')).toEqual(`Nv`);
  expect(convStr('B*8e')).toEqual(`Nu`);
  expect(convStr('R*8e')).toEqual(`Nt`);
  expect(convStr('P*8f')).toEqual(`Wz`);
  expect(convStr('L*8f')).toEqual(`Wy`);
  expect(convStr('N*8f')).toEqual(`Wx`);
  expect(convStr('S*8f')).toEqual(`Ww`);
  expect(convStr('G*8f')).toEqual(`Wv`);
  expect(convStr('B*8f')).toEqual(`Wu`);
  expect(convStr('R*8f')).toEqual(`Wt`);
  expect(convStr('P*8g')).toEqual(`\`z`);
  expect(convStr('L*8g')).toEqual(`\`y`);
  expect(convStr('N*8g')).toEqual(`\`x`);
  expect(convStr('S*8g')).toEqual(`\`w`);
  expect(convStr('G*8g')).toEqual(`\`v`);
  expect(convStr('B*8g')).toEqual(`\`u`);
  expect(convStr('R*8g')).toEqual(`\`t`);
  expect(convStr('P*8h')).toEqual(`iz`);
  expect(convStr('L*8h')).toEqual(`iy`);
  expect(convStr('N*8h')).toEqual(`ix`);
  expect(convStr('S*8h')).toEqual(`iw`);
  expect(convStr('G*8h')).toEqual(`iv`);
  expect(convStr('B*8h')).toEqual(`iu`);
  expect(convStr('R*8h')).toEqual(`it`);
  expect(convStr('P*8i')).toEqual(`rz`);
  expect(convStr('L*8i')).toEqual(`ry`);
  expect(convStr('N*8i')).toEqual(`rx`);
  expect(convStr('S*8i')).toEqual(`rw`);
  expect(convStr('G*8i')).toEqual(`rv`);
  expect(convStr('B*8i')).toEqual(`ru`);
  expect(convStr('R*8i')).toEqual(`rt`);
  expect(convStr('P*9a')).toEqual(`+z`);
  expect(convStr('L*9a')).toEqual(`+y`);
  expect(convStr('N*9a')).toEqual(`+x`);
  expect(convStr('S*9a')).toEqual(`+w`);
  expect(convStr('G*9a')).toEqual(`+v`);
  expect(convStr('B*9a')).toEqual(`+u`);
  expect(convStr('R*9a')).toEqual(`+t`);
  expect(convStr('P*9b')).toEqual(`4z`);
  expect(convStr('L*9b')).toEqual(`4y`);
  expect(convStr('N*9b')).toEqual(`4x`);
  expect(convStr('S*9b')).toEqual(`4w`);
  expect(convStr('G*9b')).toEqual(`4v`);
  expect(convStr('B*9b')).toEqual(`4u`);
  expect(convStr('R*9b')).toEqual(`4t`);
  expect(convStr('P*9c')).toEqual(`=z`);
  expect(convStr('L*9c')).toEqual(`=y`);
  expect(convStr('N*9c')).toEqual(`=x`);
  expect(convStr('S*9c')).toEqual(`=w`);
  expect(convStr('G*9c')).toEqual(`=v`);
  expect(convStr('B*9c')).toEqual(`=u`);
  expect(convStr('R*9c')).toEqual(`=t`);
  expect(convStr('P*9d')).toEqual(`Fz`);
  expect(convStr('L*9d')).toEqual(`Fy`);
  expect(convStr('N*9d')).toEqual(`Fx`);
  expect(convStr('S*9d')).toEqual(`Fw`);
  expect(convStr('G*9d')).toEqual(`Fv`);
  expect(convStr('B*9d')).toEqual(`Fu`);
  expect(convStr('R*9d')).toEqual(`Ft`);
  expect(convStr('P*9e')).toEqual(`Oz`);
  expect(convStr('L*9e')).toEqual(`Oy`);
  expect(convStr('N*9e')).toEqual(`Ox`);
  expect(convStr('S*9e')).toEqual(`Ow`);
  expect(convStr('G*9e')).toEqual(`Ov`);
  expect(convStr('B*9e')).toEqual(`Ou`);
  expect(convStr('R*9e')).toEqual(`Ot`);
  expect(convStr('P*9f')).toEqual(`Xz`);
  expect(convStr('L*9f')).toEqual(`Xy`);
  expect(convStr('N*9f')).toEqual(`Xx`);
  expect(convStr('S*9f')).toEqual(`Xw`);
  expect(convStr('G*9f')).toEqual(`Xv`);
  expect(convStr('B*9f')).toEqual(`Xu`);
  expect(convStr('R*9f')).toEqual(`Xt`);
  expect(convStr('P*9g')).toEqual(`az`);
  expect(convStr('L*9g')).toEqual(`ay`);
  expect(convStr('N*9g')).toEqual(`ax`);
  expect(convStr('S*9g')).toEqual(`aw`);
  expect(convStr('G*9g')).toEqual(`av`);
  expect(convStr('B*9g')).toEqual(`au`);
  expect(convStr('R*9g')).toEqual(`at`);
  expect(convStr('P*9h')).toEqual(`jz`);
  expect(convStr('L*9h')).toEqual(`jy`);
  expect(convStr('N*9h')).toEqual(`jx`);
  expect(convStr('S*9h')).toEqual(`jw`);
  expect(convStr('G*9h')).toEqual(`jv`);
  expect(convStr('B*9h')).toEqual(`ju`);
  expect(convStr('R*9h')).toEqual(`jt`);
  expect(convStr('P*9i')).toEqual(`sz`);
  expect(convStr('L*9i')).toEqual(`sy`);
  expect(convStr('N*9i')).toEqual(`sx`);
  expect(convStr('S*9i')).toEqual(`sw`);
  expect(convStr('G*9i')).toEqual(`sv`);
  expect(convStr('B*9i')).toEqual(`su`);
  expect(convStr('R*9i')).toEqual(`st`);
});

test('scalashogiCharPair - lion moves', () => {
  expect(convStr('5e4d3c', 'chushogi')).toEqual(`WÎ`);
  expect(convStr('5e4d4c', 'chushogi')).toEqual(`WÆ`);
  expect(convStr('5e4d5c', 'chushogi')).toEqual(`W¾`);
  expect(convStr('5e4d3d', 'chushogi')).toEqual(`W¶`);
  expect(convStr('5e4d5d', 'chushogi')).toEqual(`Wî`);
  expect(convStr('5e4d3e', 'chushogi')).toEqual(`Wæ`);
  expect(convStr('5e4d4e', 'chushogi')).toEqual(`WÞ`);
  expect(convStr('5e4d5e', 'chushogi')).toEqual(`WÖ`);
  expect(convStr('5e5d4c', 'chushogi')).toEqual(`WÍ`);
  expect(convStr('5e5d5c', 'chushogi')).toEqual(`WÅ`);
  expect(convStr('5e5d6c', 'chushogi')).toEqual(`W½`);
  expect(convStr('5e5d4d', 'chushogi')).toEqual(`Wµ`);
  expect(convStr('5e5d6d', 'chushogi')).toEqual(`Wí`);
  expect(convStr('5e5d4e', 'chushogi')).toEqual(`Wå`);
  expect(convStr('5e5d5e', 'chushogi')).toEqual(`WÝ`);
  expect(convStr('5e5d6e', 'chushogi')).toEqual(`WÕ`);
  expect(convStr('5e6d5c', 'chushogi')).toEqual(`WÌ`);
  expect(convStr('5e6d6c', 'chushogi')).toEqual(`WÄ`);
  expect(convStr('5e6d7c', 'chushogi')).toEqual(`W¼`);
  expect(convStr('5e6d5d', 'chushogi')).toEqual(`W´`);
  expect(convStr('5e6d7d', 'chushogi')).toEqual(`Wì`);
  expect(convStr('5e6d5e', 'chushogi')).toEqual(`Wä`);
  expect(convStr('5e6d6e', 'chushogi')).toEqual(`WÜ`);
  expect(convStr('5e6d7e', 'chushogi')).toEqual(`WÔ`);
  expect(convStr('5e4e3d', 'chushogi')).toEqual(`WË`);
  expect(convStr('5e4e4d', 'chushogi')).toEqual(`WÃ`);
  expect(convStr('5e4e5d', 'chushogi')).toEqual(`W»`);
  expect(convStr('5e4e3e', 'chushogi')).toEqual(`W³`);
  expect(convStr('5e4e5e', 'chushogi')).toEqual(`Wë`);
  expect(convStr('5e4e3f', 'chushogi')).toEqual(`Wã`);
  expect(convStr('5e4e4f', 'chushogi')).toEqual(`WÛ`);
  expect(convStr('5e4e5f', 'chushogi')).toEqual(`WÓ`);
  expect(convStr('5e6e5d', 'chushogi')).toEqual(`WÒ`);
  expect(convStr('5e6e6d', 'chushogi')).toEqual(`WÊ`);
  expect(convStr('5e6e7d', 'chushogi')).toEqual(`WÂ`);
  expect(convStr('5e6e5e', 'chushogi')).toEqual(`Wº`);
  expect(convStr('5e6e7e', 'chushogi')).toEqual(`Wò`);
  expect(convStr('5e6e5f', 'chushogi')).toEqual(`Wê`);
  expect(convStr('5e6e6f', 'chushogi')).toEqual(`Wâ`);
  expect(convStr('5e6e7f', 'chushogi')).toEqual(`WÚ`);
  expect(convStr('5e4f3e', 'chushogi')).toEqual(`WÑ`);
  expect(convStr('5e4f4e', 'chushogi')).toEqual(`WÉ`);
  expect(convStr('5e4f5e', 'chushogi')).toEqual(`WÁ`);
  expect(convStr('5e4f3f', 'chushogi')).toEqual(`W¹`);
  expect(convStr('5e4f5f', 'chushogi')).toEqual(`Wñ`);
  expect(convStr('5e4f3g', 'chushogi')).toEqual(`Wé`);
  expect(convStr('5e4f4g', 'chushogi')).toEqual(`Wá`);
  expect(convStr('5e4f5g', 'chushogi')).toEqual(`WÙ`);
  expect(convStr('5e5f4e', 'chushogi')).toEqual(`WÐ`);
  expect(convStr('5e5f5e', 'chushogi')).toEqual(`WÈ`);
  expect(convStr('5e5f6e', 'chushogi')).toEqual(`WÀ`);
  expect(convStr('5e5f4f', 'chushogi')).toEqual(`W¸`);
  expect(convStr('5e5f6f', 'chushogi')).toEqual(`Wð`);
  expect(convStr('5e5f4g', 'chushogi')).toEqual(`Wè`);
  expect(convStr('5e5f5g', 'chushogi')).toEqual(`Wà`);
  expect(convStr('5e5f6g', 'chushogi')).toEqual(`WØ`);
  expect(convStr('5e6f5e', 'chushogi')).toEqual(`WÏ`);
  expect(convStr('5e6f6e', 'chushogi')).toEqual(`WÇ`);
  expect(convStr('5e6f7e', 'chushogi')).toEqual(`W¿`);
  expect(convStr('5e6f5f', 'chushogi')).toEqual(`W·`);
  expect(convStr('5e6f7f', 'chushogi')).toEqual(`Wï`);
  expect(convStr('5e6f5g', 'chushogi')).toEqual(`Wç`);
  expect(convStr('5e6f6g', 'chushogi')).toEqual(`Wß`);
  expect(convStr('5e6f7g', 'chushogi')).toEqual(`W×`);
});

test('parseFairyUsi - usi prod 500', () => {
  for (const usis of usiFixture) {
    for (const usi of usis.split(' ')) {
      expect(!!parseFairyUsi(usi, 'standard')).toEqual(true);
    }
  }
});

test('parseFairyUsi - kyotoshogi', () => {
  expect(makeUsi(parseFairyUsi('P*2b', 'kyotoshogi')!)).toEqual('P*2b');
  expect(makeUsi(parseFairyUsi('+P*2b', 'kyotoshogi')!)).toEqual('R*2b');
  expect(makeUsi(parseFairyUsi('L*3d', 'kyotoshogi')!)).toEqual('L*3d');
  expect(makeUsi(parseFairyUsi('+L*3d', 'kyotoshogi')!)).toEqual('T*3d');
  expect(makeUsi(parseFairyUsi('N*1a', 'kyotoshogi')!)).toEqual('N*1a');
  expect(makeUsi(parseFairyUsi('+N*1a', 'kyotoshogi')!)).toEqual('G*1a');
  expect(makeUsi(parseFairyUsi('S*1a', 'kyotoshogi')!)).toEqual('S*1a');
  expect(makeUsi(parseFairyUsi('+S*1a', 'kyotoshogi')!)).toEqual('B*1a');
  expect(makeUsi(parseFairyUsi('1a1b', 'kyotoshogi')!)).toEqual('1a1b');
  expect(makeUsi(parseFairyUsi('1a1b+', 'kyotoshogi')!)).toEqual('1a1b+');
  expect(makeUsi(parseFairyUsi('1a1b-', 'kyotoshogi')!)).toEqual('1a1b+');
});

test('parseFairyUsi - dobutsu', () => {
  expect(makeUsi(parseFairyUsi('C*2b', 'dobutsu')!)).toEqual('P*2b');
  expect(makeUsi(parseFairyUsi('G*3d', 'dobutsu')!)).toEqual('R*3d');
  expect(makeUsi(parseFairyUsi('E*1a', 'dobutsu')!)).toEqual('B*1a');
});
