import { test } from 'node:test';
import { initialSfen, parseSfen } from '../../src/sfen.js';
import { parseUsi } from '../../src/util.js';
import { expect, perft } from '../debug.js';

// generated by shogiops - fixture
const dobutsuPerfts: [string, number, number][] = [
  ['', 1, 4],
  ['', 2, 17],
  ['', 3, 123],
  ['', 4, 976],
  ['', 5, 8122],
  ['', 6, 71677],
];

test('dobutsu perft', () => {
  dobutsuPerfts.forEach(([sfen, depth, res]) => {
    const pos = parseSfen('dobutsu', sfen || initialSfen('dobutsu')).unwrap();
    expect(perft(pos, depth)).toEqual(res);
  });
});

test('pieces in hand', () => {
  const pos = parseSfen('dobutsu', '3/1k1/3/1K1 b Pp 1').unwrap();
  expect(pos.hands.count()).toEqual(2);
});

test('moving into check and being captured', () => {
  const pos = parseSfen('dobutsu', '3/1k1/3/1K1 b - 1').unwrap();
  expect(perft(pos, 1)).toEqual(5);
  expect(pos.isLegal(parseUsi('2d2c')!)).toEqual(true);

  pos.play(parseUsi('2d2c')!);
  expect(perft(pos, 1)).toEqual(8);
  expect(pos.isLegal(parseUsi('2b2c')!)).toEqual(true);
  const posMiss = pos.clone();
  pos.play(parseUsi('2b2c')!);
  posMiss.play(parseUsi('2b1b')!);
  expect(pos.isEnd()).toEqual(true);
  expect(pos.outcome()?.result).toEqual('kingsLost');
  expect(pos.outcome()?.winner).toEqual('gote');
  expect(posMiss.isEnd()).toEqual(false);
  expect(perft(posMiss, 1)).toEqual(8);
});

test('try rule', () => {
  const pos = parseSfen('dobutsu', 'k2/2K/3/3 b - 1').unwrap();
  expect(perft(pos, 1)).toEqual(5);
  expect(pos.isLegal(parseUsi('1b1a')!)).toEqual(true);
  pos.play(parseUsi('1b1a')!);
  expect(pos.isEnd()).toEqual(true);
  expect(pos.outcome()?.result).toEqual('tryRule');
  expect(pos.outcome()?.winner).toEqual('sente');
});

test('try rule - in check', () => {
  const pos = parseSfen('dobutsu', '1r1/bpK/k2/3 b -').unwrap();
  expect(perft(pos, 1)).toEqual(5);
  expect(pos.isLegal(parseUsi('1b1a')!)).toEqual(true);
  pos.play(parseUsi('1b1a')!);
  expect(pos.isEnd()).toEqual(false);

  // opponent safe try rule
  const pos1 = pos.clone();
  expect(pos1.isLegal(parseUsi('3c3d')!)).toEqual(true);
  pos1.play(parseUsi('3c3d')!);
  expect(pos1.isEnd()).toEqual(true);
  expect(pos1.outcome()?.result).toEqual('tryRule');
  expect(pos1.outcome()?.winner).toEqual('gote');

  // random unrelated move
  const pos2 = pos.clone();
  expect(pos2.isLegal(parseUsi('2b2c')!)).toEqual(true);
  pos2.play(parseUsi('2b2c')!);
  expect(pos2.isEnd()).toEqual(false);

  // clearing check
  const pos3 = pos.clone();
  expect(pos3.isLegal(parseUsi('2a3a')!)).toEqual(true);
  pos3.play(parseUsi('2a3a')!);
  expect(pos3.isEnd()).toEqual(true);
  expect(pos3.outcome()?.result).toEqual('tryRule');
  expect(pos3.outcome()?.winner).toEqual('sente');
});

test('try rule - draw', () => {
  const pos = parseSfen('dobutsu', '1K1/1r1/1R1/1k1 w BPbp 40').unwrap();
  expect(pos.validate(true).isOk).toEqual(true);
  expect(pos.isLegal(parseUsi('2b2c')!)).toEqual(true);
  pos.play(parseUsi('2b2c')!);
  expect(pos.isEnd()).toEqual(true);
  expect(pos.outcome()?.result).toEqual('draw');
  expect(pos.outcome()?.winner).toEqual(undefined);
});

test('force promoting', () => {
  const pos = parseSfen('dobutsu', '3/BRP/2k/K2 b P').unwrap();
  expect(pos.isLegal(parseUsi('1b1a')!)).toEqual(false);
  expect(pos.isLegal(parseUsi('1b1a+')!)).toEqual(true);
  expect(pos.isLegal(parseUsi('3b2a+')!)).toEqual(false);
});

test('drops', () => {
  const pos = parseSfen('dobutsu', 'rkr/b1b/1P1/BKR b P').unwrap();
  expect(pos.isLegal(parseUsi('P*2b')!)).toEqual(true);
  pos.play(parseUsi('P*2b')!);
  expect(pos.isEnd()).toEqual(false);
});

test('valid in opposite check', () => {
  const posB = parseSfen('dobutsu', 'r2/2k/PKb/B2 b Pr').unwrap();
  const posW = parseSfen('dobutsu', 'r2/2k/PKb/B2 w Pr').unwrap();
  expect(posB.validate(true).isOk).toEqual(true);
  expect(posW.validate(true).isOk).toEqual(true);
});

test('double pawn', () => {
  const pos = parseSfen('dobutsu', 'rkb/2P/2P/BKR b - 1').unwrap();
  expect(pos.validate(true).isOk).toEqual(true);

  const posPre = parseSfen('dobutsu', 'rkb/3/2P/BKR b P 1').unwrap();
  expect(posPre.isLegal(parseUsi('P*1b')!)).toEqual(true);
});
